language: android
jdk: oraclejdk8
before_install:
- nvm install 8
- node --version
install:
- cd Example
- npm install
android:
  components:
  - build-tools-23.0.1
  - build-tools-26.0.3
  - android-26
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- cd android && ./gradlew assembleRelease
